apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: hzt-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
  - target:
      kind: Deployment
      name: hzt-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

images:
  - name: ghcr.io/ali-khamis45/hermes_zome_torba-api
    newTag: latest
  - name: ghcr.io/ali-khamis45/hermes_zome_torba-web
    newTag: latest
