apiVersion: v1
kind: Service
metadata:
  name: hzt-api
  namespace: hermes-zone-torba
  labels:
    app.kubernetes.io/name: hzt-api
spec:
  selector:
    app.kubernetes.io/name: hzt-api
  ports:
    - name: http
      port: 80
      targetPort: http
