apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hermes-zone-torba

resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: hermes-zone-torba
  app.kubernetes.io/managed-by: kustomize
